server:
    port: 8090
    servlet.context-path: /

https:
   port: 7205
   keystore-password: 123456
   keystore-file: D:/rsakey/loveshare.keystore

# 包含其他yml文件
spring:
   profiles:
     include: 'mybatis'
